In [2]:
import pandas as pd

In [4]:
patients = pd.read_csv("PATIENTS.csv")
admissions = pd.read_csv("ADMISSIONS.csv")

In [ ]:
noteEvents = pd.read_csv("NOTEEVENTS.csv")
dict_labItems = pd.read_csv('D_LABITEMS.csv')
chartEvents = pd.read_csv('CHARTEVENTS.csv')
dict_Items = pd.read_csv('D_ITEMS.csv')
diagnosesList = pd.read_csv('DIAGNOSES_ICD.csv')
dict_diagnoses = pd.read_csv('D_ICD_DIAGNOSES.csv')
drg_diag = pd.read_csv('DRGCODES.csv')
procedureEvents = pd.read_csv('PROCEDURES_ICD.csv')
dict_procedures = pd.read_csv('D_ICD_PROCEDURES.csv')
prescriptions = pd.read_csv('PRESCRIPTIONS.csv')
inputEvents_cv = pd.read_csv('INPUTEVENTS_CV.csv')
inputEvents_mv = pd.read_csv('INPUTEVENTS_MV.csv')
outputEvents = pd.read_csv('OUTPUTEVENTS.csv')

In [8]:
combinedDataTable = patients.copy();

In [9]:
combinedDataTable = pd.merge(combinedDataTable, admissions, how = 'left', on = "SUBJECT_ID")

In [11]:
combinedDataTable

,ROW_ID_x,SUBJECT_ID,GENDER,DOB,DOD,DOD_HOSP,DOD_SSN,EXPIRE_FLAG,ROW_ID_y,HADM_ID,...,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA
0,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,Medicare,NaN,CATHOLIC,DIVORCED,WHITE,2149-12-17 11:10:00,2149-12-17 21:35:00,UNSTABLE ANGINA;ASTHMA;BRONCHITIS,0,1
1,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,322,149546,...,Medicare,ENGL,CATHOLIC,DIVORCED,WHITE,2155-02-03 17:43:00,2155-02-03 21:26:00,GI BLEED/ CHEST PAIN,0,1
2,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,323,158975,...,Medicare,ENGL,CATHOLIC,DIVORCED,WHITE,NaN,NaN,GI BLEEDING\COLONOSCOPY,0,1
3,235,250,F,2164-12-27 00:00:00,2188-11-22 00:00:00,2188-11-22 00:00:00,NaN,1,324,124271,...,Self Pay,HAIT,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,2188-11-12 06:56:00,2188-11-12 10:10:00,PNEUMONIA;R/O TB,1,1
4,236,251,M,2090-03-15 00:00:00,NaN,NaN,NaN,0,325,117937,...,Private,NaN,OTHER,NaN,UNKNOWN/NOT SPECIFIED,2110-07-27 05:00:00,2110-07-27 07:15:00,INTRACRANIAL HEAD BLEED,0,1
5,237,252,M,2078-03-06 00:00:00,NaN,NaN,NaN,0,326,190159,...,Private,NaN,UNOBTAINABLE,SINGLE,WHITE,2133-03-31 03:58:00,2133-03-31 05:00:00,GASTROINTESTINAL BLEED,0,1
6,237,252,M,2078-03-06 00:00:00,NaN,NaN,NaN,0,327,193470,...,Private,NaN,UNOBTAINABLE,SINGLE,WHITE,2133-08-15 01:42:00,2133-08-15 04:45:00,GASTROINTESINAL BLEED,0,1
7,238,253,F,2089-11-26 00:00:00,NaN,NaN,NaN,0,328,176189,...,Medicare,NaN,CATHOLIC,WIDOWED,WHITE,NaN,NaN,COMPLETE HEART BLOCK\PACEMAKER IMPLANT,0,1
8,239,255,M,2109-08-05 00:00:00,NaN,NaN,NaN,0,329,112013,...,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,NaN,NaN,BENIGN PROSTATIC HYPERTROPHY/SDA,0,1
9,240,256,M,2086-07-31 00:00:00,NaN,NaN,NaN,0,330,155415,...,Medicare,NaN,NOT SPECIFIED,MARRIED,WHITE,NaN,NaN,ABDOMINAL AORTIC ANEURYSM/SDA,0,0
10,240,256,M,2086-07-31 00:00:00,NaN,NaN,NaN,0,331,153771,...,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,2166-07-21 14:34:00,2166-07-22 00:50:00,WEAKNESS;ANEMIA;TELEMETRY,0,1
11,240,256,M,2086-07-31 00:00:00,NaN,NaN,NaN,0,332,188869,...,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,2170-06-15 00:25:00,2170-06-15 02:43:00,ENDOVASCULAR AORTIC ANEURYSM,0,1
12,240,256,M,2086-07-31 00:00:00,NaN,NaN,NaN,0,333,108811,...,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,2170-08-16 09:54:00,2170-08-16 16:06:00,ABDOMINAL PAIN,0,1
13,241,257,F,2031-04-03 00:00:00,2121-07-08 00:00:00,2121-07-08 00:00:00,2121-07-08 00:00:00,1,334,179006,...,Medicare,NaN,CATHOLIC,WIDOWED,WHITE,2112-12-20 14:35:00,2112-12-20 21:19:00,SUBARACHNOID HEMORRHAGE;TELEMETRY,0,1
14,242,258,F,2124-09-19 00:00:00,NaN,NaN,NaN,0,335,189406,...,Private,NaN,NOT SPECIFIED,NaN,ASIAN,NaN,NaN,NEWBORN,0,1
15,243,260,F,2105-03-23 00:00:00,NaN,NaN,NaN,0,336,190363,...,Private,NaN,CATHOLIC,NaN,WHITE,NaN,NaN,NEWBORN,0,1
16,244,261,M,2025-08-04 00:00:00,2102-06-29 00:00:00,2102-06-29 00:00:00,2102-06-29 00:00:00,1,337,118523,...,Medicare,NaN,OTHER,MARRIED,WHITE,2101-12-26 20:11:00,2101-12-27 01:50:00,HYPOXIA,0,1
17,245,262,M,2090-01-05 00:00:00,NaN,NaN,NaN,0,338,106019,...,Private,ENGL,CATHOLIC,SINGLE,UNKNOWN/NOT SPECIFIED,NaN,NaN,HYPERTROPHIC CARDIOMYOPATHY\ETHANOL SEPTAL ABL...,0,1
18,246,263,M,2104-06-18 00:00:00,2168-06-13 00:00:00,2168-06-13 00:00:00,NaN,1,339,120845,...,Private,NaN,CATHOLIC,MARRIED,WHITE,2160-01-09 11:42:00,2160-01-09 22:04:00,PERIPHERAL INSUFFICIENCY;RIGHT FOOT,0,1
19,247,264,F,2162-11-30 00:00:00,NaN,NaN,NaN,0,340,136714,...,Private,NaN,JEWISH,NaN,WHITE,NaN,NaN,NEWBORN,0,1
20,248,265,M,2093-08-01 00:00:00,NaN,NaN,NaN,0,341,101608,...,Private,ENGL,OTHER,MARRIED,WHITE,NaN,NaN,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,0,1
21,249,266,F,2090-12-17 00:00:00,NaN,NaN,NaN,0,342,186251,...,Medicare,ENGL,JEHOVAH'S WITNESS,WIDOWED,BLACK/AFRICAN AMERICAN,2168-07-10 05:05:00,2168-07-10 09:02:00,SEIZURE,0,1
22,250,267,F,2131-09-05 00:00:00,NaN,NaN,NaN,0,343,163714,...,Private,ENGL,BUDDHIST,MARRIED,ASIAN - ASIAN INDIAN,NaN,NaN,PANCREATITIS,0,1
23,251,268,F,2132-02-21 00:00:00,2198-02-18 00:00:00,2198-02-18 00:00:00,NaN,1,344,110404,...,Medicare,NaN,CATHOLIC,SEPARATED,HISPANIC OR LATINO,2198-02-11 09:41:00,2198-02-11 15:18:00,DYSPNEA,1,1
24,252,269,M,2130-09-30 00:00:00,NaN,NaN,NaN,0,345,106296,...,Medicaid,NaN,UNOBTAINABLE,SINGLE,WHITE,2170-11-05 07:22:00,2170-11-05 12:15:00,SEPSIS;PILONIDAL ABSCESS,0,1
25,253,270,M,2048-05-26 00:00:00,NaN,NaN,NaN,0,346,188028,...,Medicare,NaN,JEHOVAH'S WITNESS,MARRIED,UNKNOWN/NOT SPECIFIED,NaN,NaN,CAROTID STENOSIS\CAROTID ANGIOGRAM AND STENT,0,1
26,626,663,F,2086-05-12 00:00:00,NaN,NaN,NaN,0,816,177445,...,Private,NaN,JEWISH,MARRIED,WHITE,NaN,NaN,ACHALASIA/SDA,0,1
27,627,664,F,2097-04-12 00:00:00,2179-04-03 00:00:00,NaN,2179-04-03 00:00:00,1,817,181314,...,Medicare,NaN,NaN,MARRIED,UNKNOWN/NOT SPECIFIED,NaN,NaN,UNSTABLE ANGINA,0,1
28,628,665,M,2052-05-20 00:00:00,2120-02-04 00:00:00,2120-02-04 00:00:00,NaN,1,818,126226,...,Government,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,NaN,NaN,CORONARY ARTERY DISEASE;PVD\R HEART CATH;PERIP...,0,1
29,628,665,M,2052-05-20 00:00:00,2120-02-04 00:00:00,2120-02-04 00:00:00,NaN,1,819,152089,...,Medicaid,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,2119-02-25 16:38:00,2119-02-25 21:00:00,SYNCOPE;TELEMETRY,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58946,31820,44016,M,2104-08-05 00:00:00,NaN,NaN,NaN,0,41032,122419,...,Medicare,ENGL,CATHOLIC,DIVORCED,WHITE,NaN,NaN,AORTIC VALVE DISORDER\AORTIC VALVE / ASCENDING...,0,1
58947,31821,44018,F,2067-06-11 00:00:00,2155-11-27 00:00:00,2155-11-27 00:00:00,2155-11-27 00:00:00,1,41033,113295,...,Medicare,ENGL,UNOBTAINABLE,NaN,UNKNOWN/NOT SPECIFIED,2155-10-20 23:07:00,2155-10-21 03:15:00,PANCREATITS,1,1
58948,31822,44019,F,1901-01-14 00:00:00,2201-01-14 00:00:00,2201-01-14 00:00:00,2201-01-14 00:00:00,1,41034,125484,...,Medicare,NaN,NOT SPECIFIED,MARRIED,UNKNOWN/NOT SPECIFIED,2201-01-13 23:23:00,2201-01-14 00:10:00,ST ELEVATED MYOCARDIAL INFARCTION,1,1
58949,31823,44023,M,2107-02-25 00:00:00,NaN,NaN,NaN,0,41035,148889,...,Private,ENGL,NOT SPECIFIED,DIVORCED,WHITE,NaN,NaN,ATRIAL FRIBILLATION\BILATERAL THORACOSCOPIC MI...,0,1
58950,31824,44035,F,2054-12-30 00:00:00,NaN,NaN,NaN,0,41036,114515,...,Medicare,ENGL,UNOBTAINABLE,MARRIED,WHITE,NaN,NaN,CONGESTIVE HEART FAILURE,0,1
58951,31825,44036,F,2132-05-07 00:00:00,NaN,NaN,NaN,0,41037,170297,...,Private,ENGL,CATHOLIC,MARRIED,WHITE,2186-08-21 23:50:00,2186-08-22 04:27:00,SEPSIS;INFECTED RENAL STONE,0,1
58952,31826,44038,M,2060-07-06 00:00:00,NaN,NaN,NaN,0,41038,156006,...,Medicaid,HAIT,UNOBTAINABLE,SINGLE,BLACK/HAITIAN,2120-12-23 07:51:00,2120-12-23 08:32:00,ST ELEVATED MYOCARDIAL INFARCTION,0,1
58953,31827,44044,M,2032-07-21 00:00:00,NaN,NaN,NaN,0,41039,127194,...,Medicare,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,2105-03-07 13:20:00,2105-03-07 18:42:00,HYPOTENSION,0,1
58954,31828,44052,M,2114-04-03 00:00:00,NaN,NaN,NaN,0,41040,162646,...,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,NaN,NaN,AORTIC VALVE STENOSIS\AORTIC VALVE REPLACEMENT...,0,1
58955,31829,44058,M,2102-06-28 00:00:00,2156-01-07 00:00:00,NaN,2156-01-07 00:00:00,1,41041,189308,...,Government,ENGL,UNOBTAINABLE,SINGLE,WHITE,2155-10-08 22:50:00,2155-10-09 02:17:00,DIABETIC KETOACIDOSIS,0,1
58956,31830,44059,F,2051-03-25 00:00:00,2127-08-07 00:00:00,2127-08-07 00:00:00,NaN,1,41042,198015,...,Medicare,ENGL,PROTESTANT QUAKER,SINGLE,BLACK/AFRICAN AMERICAN,2127-07-24 15:02:00,2127-07-24 19:59:00,CHEST PAIN,1,1
58957,31831,44061,M,2073-09-29 00:00:00,NaN,NaN,NaN,0,41043,107667,...,Private,ENGL,PROTESTANT QUAKER,MARRIED,WHITE,NaN,NaN,LIVER LESION\RADIOFREQUENCY ABLATION LIVER LES...,0,1
58958,31831,44061,M,2073-09-29 00:00:00,NaN,NaN,NaN,0,41044,181541,...,Private,ENGL,PROTESTANT QUAKER,MARRIED,WHITE,NaN,NaN,LIVER FAILURE,0,1
58959,31832,44064,M,2115-11-18 00:00:00,NaN,NaN,NaN,0,41045,189505,...,Medicare,ENGL,OTHER,SINGLE,WHITE,2200-02-23 21:09:00,2200-02-24 00:10:00,UNRESPONSIVE,0,1
58960,31832,44064,M,2115-11-18 00:00:00,NaN,NaN,NaN,0,41046,126583,...,Medicare,ENGL,OTHER,SINGLE,WHITE,2200-04-20 18:39:00,2200-04-21 02:57:00,FEVER,0,1
58961,31832,44064,M,2115-11-18 00:00:00,NaN,NaN,NaN,0,41047,136380,...,Medicare,ENGL,OTHER,SINGLE,WHITE,2200-04-27 13:52:00,2200-04-27 17:52:00,"PNA,CHF",0,1
58962,31833,44065,M,2116-03-30 00:00:00,NaN,NaN,NaN,0,41048,135334,...,Private,ENGL,NOT SPECIFIED,MARRIED,PATIENT DECLINED TO ANSWER,NaN,NaN,ISCHEMIC RIGHT LEG,0,1
58963,31834,44069,M,2064-04-08 00:00:00,NaN,NaN,NaN,0,41049,138192,...,Private,ENGL,PROTESTANT QUAKER,MARRIED,WHITE,NaN,NaN,CORONARY ARTERY DISEASE,0,1
58964,31835,44071,M,2097-11-14 00:00:00,NaN,NaN,NaN,0,41050,153383,...,Private,ENGL,OTHER,MARRIED,OTHER,NaN,NaN,ATRIAL FLUTTER\ATRIAL FLUTTER ABLATION,0,1
58965,31836,44073,F,2086-03-29 00:00:00,NaN,NaN,NaN,0,41051,183835,...,Medicare,ENGL,CATHOLIC,WIDOWED,WHITE,NaN,NaN,CORONARY ARTERY DISEASE;AORTIC STENOSIS;MITRAL...,0,1
58966,31837,44082,F,2056-04-27 00:00:00,NaN,NaN,NaN,0,41052,178322,...,Medicare,ENGL,CATHOLIC,DIVORCED,WHITE,NaN,NaN,CORONARY ARTERY DISEASE,0,1
58967,31838,44083,M,2057-11-15 00:00:00,2114-02-20 00:00:00,2114-02-20 00:00:00,2114-02-20 00:00:00,1,41053,125157,...,Private,ENGL,CATHOLIC,SINGLE,WHITE,NaN,NaN,ESOPHAGEAL CA/SDA,0,1
58968,31838,44083,M,2057-11-15 00:00:00,2114-02-20 00:00:00,2114-02-20 00:00:00,2114-02-20 00:00:00,1,41054,131048,...,Private,ENGL,CATHOLIC,SINGLE,WHITE,2112-05-22 09:25:00,2112-05-22 17:04:00,SHORTNESS OF BREATH,0,1
58969,31838,44083,M,2057-11-15 00:00:00,2114-02-20 00:00:00,2114-02-20 00:00:00,2114-02-20 00:00:00,1,41055,198330,...,Private,ENGL,CATHOLIC,SINGLE,WHITE,2112-05-28 13:16:00,2112-05-28 17:30:00,PERICARDIAL EFFUSION,0,1
58970,31839,44084,F,2057-07-18 00:00:00,NaN,NaN,NaN,0,41056,174828,...,Medicare,ENGL,PROTESTANT QUAKER,SINGLE,OTHER,NaN,NaN,CORONARY ARTERY DISEASE\OFF PUMP CORONARY ARTE...,0,1
58971,31840,44089,M,2026-05-25 00:00:00,NaN,NaN,NaN,0,41057,165748,...,Medicare,ENGL,GREEK ORTHODOX,MARRIED,WHITE,2111-09-29 18:35:00,2111-09-30 07:08:00,CHEST PAIN;ANGINA\LEFT HEART CATHETERIZATION,0,1
58972,31841,44115,F,2124-07-27 00:00:00,NaN,NaN,NaN,0,41058,163623,...,Private,ENGL,CATHOLIC,MARRIED,WHITE,NaN,NaN,CHIARI MALFORMATION BILATERAL/SDA,0,1
58973,31842,44123,F,2049-11-26 00:00:00,2135-01-12 00:00:00,2135-01-12 00:00:00,NaN,1,41059,116395,...,Medicare,NaN,CATHOLIC,SEPARATED,WHITE,NaN,NaN,ABDOMINAL ANEURYSM; NO RUPTURE/SDA,1,1
58974,31843,44126,F,2076-07-25 00:00:00,NaN,NaN,NaN,0,41060,183530,...,Private,ENGL,NOT SPECIFIED,MARRIED,WHITE,NaN,NaN,SCOLIOSIS/SDA,0,1
58975,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,Private,ENGL,NOT SPECIFIED,MARRIED,WHITE,2149-06-08 11:53:00,2149-06-08 15:31:00,TRAUMA,0,1

In [ ]:
labEvents = pd.read_csv('LABEVENTS.csv')
dict_labItems = pd.read_csv('D_LABITEMS.csv')

In [14]:
combinedLab = pd.merge(labEvents, dict_labItems, how = 'left', on = "ITEMID")
combinedLab

,ROW_ID_x,SUBJECT_ID,HADM_ID,ITEMID,CHARTTIME,VALUE,VALUENUM,VALUEUOM,FLAG,ROW_ID_y,LABEL,FLUID,CATEGORY,LOINC_CODE
0,281,3,NaN,50820,2101-10-12 16:07:00,7.39,7.39,units,NaN,21,pH,Blood,Blood Gas,11558-4
1,282,3,NaN,50800,2101-10-12 18:17:00,ART,NaN,NaN,NaN,1,SPECIMEN TYPE,BLOOD,BLOOD GAS,NaN
2,283,3,NaN,50802,2101-10-12 18:17:00,-1,-1.00,mEq/L,NaN,3,Base Excess,Blood,Blood Gas,11555-0
3,284,3,NaN,50804,2101-10-12 18:17:00,22,22.00,mEq/L,NaN,5,Calculated Total CO2,Blood,Blood Gas,34728-6
4,285,3,NaN,50808,2101-10-12 18:17:00,0.93,0.93,mmol/L,abnormal,9,Free Calcium,Blood,Blood Gas,1994-3
5,286,3,NaN,50812,2101-10-12 18:17:00,NOT INTUBATED,NaN,NaN,NaN,13,Intubated,Blood,Blood Gas,NaN
6,287,3,NaN,50813,2101-10-12 18:17:00,1.8,1.80,mmol/L,NaN,14,Lactate,Blood,Blood Gas,32693-4
7,288,3,NaN,50818,2101-10-12 18:17:00,33,33.00,mm Hg,NaN,19,pCO2,Blood,Blood Gas,11557-6
8,289,3,NaN,50820,2101-10-12 18:17:00,7.42,7.42,units,NaN,21,pH,Blood,Blood Gas,11558-4
9,290,3,NaN,50821,2101-10-12 18:17:00,80,80.00,mm Hg,NaN,22,pO2,Blood,Blood Gas,11556-8
10,291,3,NaN,50825,2101-10-12 18:17:00,35.8,35.80,NaN,NaN,26,Temperature,Blood,Blood Gas,NaN
11,292,3,NaN,50868,2101-10-13 03:00:00,13,13.00,mEq/L,NaN,69,Anion Gap,Blood,Chemistry,1863-0
12,293,3,NaN,50882,2101-10-13 03:00:00,23,23.00,mEq/L,NaN,83,Bicarbonate,Blood,Chemistry,1963-8
13,294,3,NaN,50893,2101-10-13 03:00:00,8.4,8.40,mg/dL,NaN,94,"Calcium, Total",Blood,Chemistry,2000-8
14,295,3,NaN,50902,2101-10-13 03:00:00,109,109.00,mEq/L,NaN,103,Chloride,Blood,Chemistry,2075-0
15,296,3,NaN,50912,2101-10-13 03:00:00,1.7,1.70,mg/dL,abnormal,113,Creatinine,Blood,Chemistry,2160-0
16,297,3,NaN,50931,2101-10-13 03:00:00,137,137.00,mg/dL,abnormal,132,Glucose,Blood,Chemistry,2345-7
17,298,3,NaN,50960,2101-10-13 03:00:00,1.8,1.80,mg/dL,NaN,161,Magnesium,Blood,Chemistry,2601-3
18,299,3,NaN,50970,2101-10-13 03:00:00,3.7,3.70,mg/dL,NaN,171,Phosphate,Blood,Chemistry,2777-1
19,300,3,NaN,50971,2101-10-13 03:00:00,4.3,4.30,mEq/L,NaN,172,Potassium,Blood,Chemistry,2823-3
20,301,3,NaN,50983,2101-10-13 03:00:00,141,141.00,mEq/L,NaN,184,Sodium,Blood,Chemistry,2951-2
21,302,3,NaN,51006,2101-10-13 03:00:00,33,33.00,mg/dL,abnormal,206,Urea Nitrogen,Blood,Chemistry,3094-0
22,303,3,NaN,51009,2101-10-13 03:00:00,16.8,16.80,ug/mL,abnormal,209,Vancomycin,Blood,Chemistry,20578-1
23,304,3,NaN,51221,2101-10-13 03:00:00,30.3,30.30,%,abnormal,421,Hematocrit,Blood,Hematology,4544-3
24,305,3,NaN,50868,2101-10-13 15:47:00,14,14.00,mEq/L,NaN,69,Anion Gap,Blood,Chemistry,1863-0
25,306,3,NaN,50882,2101-10-13 15:47:00,25,25.00,mEq/L,NaN,83,Bicarbonate,Blood,Chemistry,1963-8
26,307,3,NaN,50893,2101-10-13 15:47:00,8.2,8.20,mg/dL,abnormal,94,"Calcium, Total",Blood,Chemistry,2000-8
27,308,3,NaN,50902,2101-10-13 15:47:00,107,107.00,mEq/L,NaN,103,Chloride,Blood,Chemistry,2075-0
28,309,3,NaN,50912,2101-10-13 15:47:00,1.5,1.50,mg/dL,abnormal,113,Creatinine,Blood,Chemistry,2160-0
29,310,3,NaN,50931,2101-10-13 15:47:00,152,152.00,mg/dL,abnormal,132,Glucose,Blood,Chemistry,2345-7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27854025,27428410,96443,103219.0,50821,2109-12-29 21:17:00,63,63.00,mm Hg,abnormal,22,pO2,Blood,Blood Gas,11556-8
27854026,27428411,96443,103219.0,50822,2109-12-29 21:17:00,4.7,4.70,mEq/L,NaN,23,"Potassium, Whole Blood",Blood,Blood Gas,6298-4
27854027,27428412,96443,103219.0,50825,2109-12-29 21:17:00,36.7,36.70,NaN,NaN,26,Temperature,Blood,Blood Gas,NaN
27854028,27428413,96443,103219.0,50800,2109-12-29 22:11:00,MIX,NaN,NaN,NaN,1,SPECIMEN TYPE,BLOOD,BLOOD GAS,NaN
27854029,27428414,96443,103219.0,50802,2109-12-29 22:11:00,2,2.00,mEq/L,NaN,3,Base Excess,Blood,Blood Gas,11555-0
27854030,27428415,96443,103219.0,50804,2109-12-29 22:11:00,33,33.00,mEq/L,abnormal,5,Calculated Total CO2,Blood,Blood Gas,34728-6
27854031,27428416,96443,103219.0,50812,2109-12-29 22:11:00,INTUBATED,NaN,NaN,NaN,13,Intubated,Blood,Blood Gas,NaN
27854032,27428417,96443,103219.0,50818,2109-12-29 22:11:00,62,62.00,mm Hg,abnormal,19,pCO2,Blood,Blood Gas,11557-6
27854033,27428418,96443,103219.0,50820,2109-12-29 22:11:00,7.31,7.31,units,abnormal,21,pH,Blood,Blood Gas,11558-4
27854034,27428419,96443,103219.0,50821,2109-12-29 22:11:00,45,45.00,mm Hg,abnormal,22,pO2,Blood,Blood Gas,11556-8
27854035,27428420,96443,103219.0,50825,2109-12-29 22:11:00,37.2,37.20,NaN,NaN,26,Temperature,Blood,Blood Gas,NaN
27854036,27428421,96443,103219.0,50800,2109-12-29 23:04:00,ART,NaN,NaN,NaN,1,SPECIMEN TYPE,BLOOD,BLOOD GAS,NaN
27854037,27428422,96443,103219.0,50802,2109-12-29 23:04:00,1,1.00,mEq/L,NaN,3,Base Excess,Blood,Blood Gas,11555-0
27854038,27428423,96443,103219.0,50804,2109-12-29 23:04:00,29,29.00,mEq/L,NaN,5,Calculated Total CO2,Blood,Blood Gas,34728-6
27854039,27428424,96443,103219.0,50812,2109-12-29 23:04:00,INTUBATED,NaN,NaN,NaN,13,Intubated,Blood,Blood Gas,NaN
27854040,27428425,96443,103219.0,50818,2109-12-29 23:04:00,49,49.00,mm Hg,abnormal,19,pCO2,Blood,Blood Gas,11557-6
27854041,27428426,96443,103219.0,50820,2109-12-29 23:04:00,7.37,7.37,units,NaN,21,pH,Blood,Blood Gas,11558-4
27854042,27428427,96443,103219.0,50821,2109-12-29 23:04:00,88,88.00,mm Hg,NaN,22,pO2,Blood,Blood Gas,11556-8
27854043,27428428,96443,103219.0,50825,2109-12-29 23:04:00,38.3,38.30,NaN,NaN,26,Temperature,Blood,Blood Gas,NaN
27854044,27428429,96443,103219.0,50861,2109-12-30 01:40:00,104,104.00,IU/L,abnormal,62,Alanine Aminotransferase (ALT),Blood,Chemistry,1742-6
27854045,27428430,96443,103219.0,50862,2109-12-30 01:40:00,2.2,2.20,g/dL,abnormal,63,Albumin,Blood,Chemistry,1751-7
27854046,27428431,96443,103219.0,50863,2109-12-30 01:40:00,172,172.00,IU/L,abnormal,64,Alkaline Phosphatase,Blood,Chemistry,6768-6
27854047,27428432,96443,103219.0,50867,2109-12-30 01:40:00,28,28.00,IU/L,NaN,68,Amylase,Blood,Chemistry,1798-8
27854048,27428433,96443,103219.0,50868,2109-12-30 01:40:00,15,15.00,mEq/L,NaN,69,Anion Gap,Blood,Chemistry,1863-0
27854049,27428434,96443,103219.0,50878,2109-12-30 01:40:00,467,467.00,IU/L,abnormal,79,Asparate Aminotransferase (AST),Blood,Chemistry,1920-8
27854050,27428435,96443,103219.0,50882,2109-12-30 01:40:00,26,26.00,mEq/L,NaN,83,Bicarbonate,Blood,Chemistry,1963-8
27854051,27428436,96443,103219.0,50885,2109-12-30 01:40:00,2.1,2.10,mg/dL,abnormal,86,"Bilirubin, Total",Blood,Chemistry,1975-2
27854052,27428437,96443,103219.0,50902,2109-12-30 01:40:00,97,97.00,mEq/L,NaN,103,Chloride,Blood,Chemistry,2075-0
27854053,27428438,96443,103219.0,50911,2109-12-30 01:40:00,2,2.00,ng/mL,NaN,112,"Creatine Kinase, MB Isoenzyme",Blood,Chemistry,6773-6
27854054,27428439,96443,103219.0,50912,2109-12-30 01:40:00,1.6,1.60,mg/dL,abnormal,113,Creatinine,Blood,Chemistry,2160-0

In [15]:
combinedDataTable = pd.merge(combinedDataTable, combinedLab, how = 'left', on = 'SUBJECT_ID')

In [19]:
combinedDataTable

,ROW_ID_x_x,SUBJECT_ID,GENDER,DOB,DOD,DOD_HOSP,DOD_SSN,EXPIRE_FLAG,ROW_ID_y_x,HADM_ID_x,...,CHARTTIME,VALUE,VALUENUM,VALUEUOM,FLAG,ROW_ID_y_y,LABEL,FLUID,CATEGORY,LOINC_CODE
0,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-28 06:55:00,1.4,1.40,NaN,NaN,437.0,INR(PT),Blood,Hematology,5895-7
1,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-28 06:55:00,29.7,29.70,pg,NaN,448.0,MCH,Blood,Hematology,785-6
2,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-28 06:55:00,33.4,33.40,%,NaN,449.0,MCHC,Blood,Hematology,786-4
3,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-28 06:55:00,89,89.00,fL,NaN,450.0,MCV,Blood,Hematology,787-2
4,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-28 06:55:00,260,260.00,K/uL,NaN,465.0,Platelet Count,Blood,Hematology,777-3
5,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-28 06:55:00,15.1,15.10,sec,abnormal,474.0,PT,Blood,Hematology,5902-2
6,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-28 06:55:00,54.3,54.30,sec,abnormal,475.0,PTT,Blood,Hematology,3173-2
7,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-28 06:55:00,14.0,14.00,%,NaN,477.0,RDW,Blood,Hematology,788-0
8,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-28 06:55:00,4.23,4.23,m/uL,NaN,479.0,Red Blood Cells,Blood,Hematology,789-8
9,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-28 06:55:00,15.3,15.30,K/uL,abnormal,501.0,White Blood Cells,Blood,Hematology,804-5
10,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,118,118.00,IU/L,abnormal,62.0,Alanine Aminotransferase (ALT),Blood,Chemistry,1742-6
11,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,3.2,3.20,g/dL,abnormal,63.0,Albumin,Blood,Chemistry,1751-7
12,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,105,105.00,IU/L,NaN,64.0,Alkaline Phosphatase,Blood,Chemistry,6768-6
13,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,11,11.00,mEq/L,NaN,69.0,Anion Gap,Blood,Chemistry,1863-0
14,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,79,79.00,IU/L,abnormal,79.0,Asparate Aminotransferase (AST),Blood,Chemistry,1920-8
15,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,30,30.00,mEq/L,abnormal,83.0,Bicarbonate,Blood,Chemistry,1963-8
16,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,2.0,2.00,mg/dL,abnormal,86.0,"Bilirubin, Total",Blood,Chemistry,1975-2
17,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,101,101.00,mEq/L,NaN,103.0,Chloride,Blood,Chemistry,2075-0
18,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,1.3,1.30,mg/dL,abnormal,113.0,Creatinine,Blood,Chemistry,2160-0
19,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,109,109.00,mg/dL,abnormal,132.0,Glucose,Blood,Chemistry,2345-7
20,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,1.5,1.50,mg/dL,abnormal,161.0,Magnesium,Blood,Chemistry,2601-3
21,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,4.2,4.20,mEq/L,NaN,172.0,Potassium,Blood,Chemistry,2823-3
22,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,138,138.00,mEq/L,NaN,184.0,Sodium,Blood,Chemistry,2951-2
23,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,41,41.00,mg/dL,abnormal,206.0,Urea Nitrogen,Blood,Chemistry,3094-0
24,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,34.9,34.90,%,abnormal,421.0,Hematocrit,Blood,Hematology,4544-3
25,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,12.3,12.30,g/dL,NaN,422.0,Hemoglobin,Blood,Hematology,718-7
26,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,1.5,1.50,NaN,NaN,437.0,INR(PT),Blood,Hematology,5895-7
27,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,31.0,31.00,pg,NaN,448.0,MCH,Blood,Hematology,785-6
28,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,35.3,35.30,%,abnormal,449.0,MCHC,Blood,Hematology,786-4
29,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0,321,116935,...,2149-12-29 06:55:00,88,88.00,fL,NaN,450.0,MCV,Blood,Hematology,787-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57516678,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-13 01:17:00,94,94.00,fL,NaN,450.0,MCV,Blood,Hematology,787-2
57516679,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-13 01:17:00,321,321.00,K/uL,NaN,465.0,Platelet Count,Blood,Hematology,777-3
57516680,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-13 01:17:00,13.8,13.80,%,NaN,477.0,RDW,Blood,Hematology,788-0
57516681,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-13 01:17:00,3.05,3.05,m/uL,abnormal,479.0,Red Blood Cells,Blood,Hematology,789-8
57516682,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-13 01:17:00,16.7,16.70,K/uL,abnormal,501.0,White Blood Cells,Blood,Hematology,804-5
57516683,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,13,13.00,mEq/L,NaN,69.0,Anion Gap,Blood,Chemistry,1863-0
57516684,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,31,31.00,mEq/L,NaN,83.0,Bicarbonate,Blood,Chemistry,1963-8
57516685,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,8.0,8.00,mg/dL,abnormal,94.0,"Calcium, Total",Blood,Chemistry,2000-8
57516686,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,99,99.00,mEq/L,NaN,103.0,Chloride,Blood,Chemistry,2075-0
57516687,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,0.7,0.70,mg/dL,NaN,113.0,Creatinine,Blood,Chemistry,2160-0
57516688,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,111,111.00,mg/dL,abnormal,132.0,Glucose,Blood,Chemistry,2345-7
57516689,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,2.1,2.10,mg/dL,NaN,161.0,Magnesium,Blood,Chemistry,2601-3
57516690,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,1.9,1.90,mg/dL,abnormal,171.0,Phosphate,Blood,Chemistry,2777-1
57516691,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,3.8,3.80,mEq/L,NaN,172.0,Potassium,Blood,Chemistry,2823-3
57516692,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,139,139.00,mEq/L,NaN,184.0,Sodium,Blood,Chemistry,2951-2
57516693,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,22,22.00,mg/dL,abnormal,206.0,Urea Nitrogen,Blood,Chemistry,3094-0
57516694,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,28.2,28.20,%,abnormal,421.0,Hematocrit,Blood,Hematology,4544-3
57516695,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,9.5,9.50,g/dL,abnormal,422.0,Hemoglobin,Blood,Hematology,718-7
57516696,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,1.1,1.10,NaN,NaN,437.0,INR(PT),Blood,Hematology,5895-7
57516697,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,31.9,31.90,pg,NaN,448.0,MCH,Blood,Hematology,785-6
57516698,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,33.7,33.70,%,NaN,449.0,MCHC,Blood,Hematology,786-4
57516699,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,95,95.00,fL,NaN,450.0,MCV,Blood,Hematology,787-2
57516700,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,345,345.00,K/uL,NaN,465.0,Platelet Count,Blood,Hematology,777-3
57516701,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,12.8,12.80,sec,NaN,474.0,PT,Blood,Hematology,5902-2
57516702,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,26.4,26.40,sec,NaN,475.0,PTT,Blood,Hematology,3173-2
57516703,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,13.6,13.60,%,NaN,477.0,RDW,Blood,Hematology,788-0
57516704,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,2.98,2.98,m/uL,abnormal,479.0,Red Blood Cells,Blood,Hematology,789-8
57516705,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-14 05:00:00,11.4,11.40,K/uL,abnormal,501.0,White Blood Cells,Blood,Hematology,804-5
57516706,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-15 04:45:00,27.3,27.30,%,abnormal,421.0,Hematocrit,Blood,Hematology,4544-3
57516707,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0,41061,141304,...,2149-06-16 12:22:00,28.0,28.00,%,abnormal,421.0,Hematocrit,Blood,Hematology,4544-3

In [ ]:
combinedDataTable.to_csv("pat_labs.csv", index = False)