In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [3]:
master = pd.read_csv('masterDrugs.csv')
master = master.dropna()

In [4]:
##divide master randomly into train and test
choose = np.random.rand(len(master)) < 0.8
train = master[choose]
test = master[~choose]

In [5]:
#train model
variables = train.drop(columns=['SUBJECT_ID', 'delirium'])
output = train['delirium']
model = LinearRegression().fit(variables, output)

In [10]:
#use model
test_var = test.drop(columns=['SUBJECT_ID', 'delirium'])
predicted = model.predict(test_var)
test['predicted delirium'] = predicted
test

,SUBJECT_ID,benzodiazepine,opioid,anticholinergic,steroid,deep sedation,delirium,predicted delirium
6,52,1.0,1.0,1.0,0.0,0.0,0,0.167182
10,107,0.0,1.0,0.0,1.0,1.0,0,0.161550
23,109,1.0,1.0,1.0,1.0,1.0,1,0.306989
29,6,0.0,1.0,1.0,1.0,0.0,0,0.192444
33,20,1.0,1.0,1.0,0.0,1.0,0,0.199354
40,320,0.0,0.0,0.0,0.0,0.0,0,-0.004861
41,321,1.0,1.0,1.0,0.0,0.0,1,0.167182
46,346,1.0,1.0,1.0,1.0,1.0,0,0.306989
59,373,1.0,1.0,1.0,0.0,1.0,0,0.199354
62,378,0.0,1.0,1.0,0.0,1.0,1,0.116983
65,384,1.0,0.0,1.0,0.0,0.0,1,0.140579
85,199,1.0,1.0,1.0,0.0,1.0,0,0.199354
94,249,1.0,1.0,1.0,1.0,1.0,0,0.306989
95,249,1.0,1.0,1.0,1.0,1.0,0,0.306989
99,270,0.0,1.0,1.0,1.0,0.0,0,0.192444
100,283,1.0,0.0,1.0,0.0,1.0,0,0.172752
104,291,1.0,0.0,0.0,1.0,0.0,0,0.185146
108,885,1.0,1.0,1.0,0.0,1.0,0,0.199354
115,909,0.0,0.0,1.0,1.0,0.0,0,0.165841
125,518,1.0,1.0,1.0,0.0,1.0,1,0.199354
145,634,1.0,1.0,1.0,1.0,1.0,0,0.306989
146,641,0.0,1.0,1.0,0.0,1.0,0,0.116983
163,561,0.0,1.0,0.0,0.0,1.0,0,0.053915
164,419,1.0,1.0,1.0,1.0,1.0,0,0.306989
165,420,0.0,1.0,1.0,1.0,0.0,0,0.192444
170,437,0.0,1.0,0.0,0.0,0.0,0,0.021742
178,832,1.0,1.0,1.0,0.0,0.0,1,0.167182
183,971,1.0,0.0,0.0,0.0,1.0,0,0.109684
184,974,1.0,1.0,0.0,0.0,0.0,0,0.104114
187,984,1.0,1.0,1.0,1.0,0.0,0,0.274816
...,...,...,...,...,...,...,...,...
11808,99521,0.0,0.0,0.0,0.0,0.0,0,-0.004861
11811,93679,1.0,1.0,1.0,1.0,1.0,0,0.306989
11813,93718,0.0,0.0,1.0,0.0,0.0,1,0.058207
11814,93722,0.0,1.0,1.0,1.0,0.0,0,0.192444
11817,90549,0.0,0.0,0.0,1.0,1.0,0,0.134947
11820,90626,0.0,0.0,1.0,0.0,0.0,0,0.058207
11823,92314,0.0,1.0,1.0,0.0,0.0,0,0.084810
11836,99564,1.0,1.0,1.0,0.0,1.0,0,0.199354
11839,99660,0.0,1.0,1.0,1.0,0.0,0,0.192444
11840,99669,1.0,1.0,1.0,0.0,1.0,1,0.199354
11841,95694,1.0,0.0,1.0,0.0,0.0,0,0.140579
11842,95706,0.0,1.0,1.0,0.0,1.0,0,0.116983
11845,97672,1.0,0.0,1.0,0.0,0.0,0,0.140579
11846,97677,0.0,1.0,1.0,0.0,1.0,0,0.116983
11853,92352,0.0,1.0,1.0,0.0,1.0,0,0.116983
11856,94258,1.0,1.0,1.0,0.0,0.0,0,0.167182
11857,94264,1.0,1.0,1.0,1.0,0.0,1,0.274816
11885,97781,1.0,1.0,0.0,0.0,0.0,0,0.104114
11893,96197,0.0,0.0,0.0,0.0,0.0,0,-0.004861
11905,91242,1.0,1.0,1.0,1.0,0.0,0,0.274816
11906,90484,1.0,1.0,1.0,0.0,1.0,1,0.199354
11914,93755,1.0,1.0,0.0,0.0,1.0,0,0.136287
11915,93780,0.0,1.0,1.0,0.0,1.0,0,0.116983
11916,93842,0.0,1.0,0.0,0.0,0.0,0,0.021742
11920,96260,0.0,1.0,1.0,1.0,1.0,1,0.224617
11925,90699,1.0,1.0,1.0,0.0,1.0,1,0.199354
11932,98634,1.0,1.0,1.0,0.0,1.0,0,0.199354
11935,98647,0.0,1.0,0.0,0.0,1.0,1,0.053915
11939,98687,0.0,1.0,1.0,0.0,0.0,0,0.084810
11940,98697,0.0,1.0,1.0,1.0,0.0,0,0.192444

In [45]:
coeff = variables.T
coeff['coefficients'] = model.coef_
coeff = pd.DataFrame(coeff['coefficients'])
coeff

                 coefficients
benzodiazepine       0.082372
opioid               0.026603
anticholinergic      0.063067
steroid              0.107635
deep sedation        0.032173

In [9]:
##evaluate model
R_squared = model.score(variables, output)
print("R squared coefficient: " + str(R_squared))

print('Mean Absolute Error:', metrics.mean_absolute_error(test['delirium'], test['predicted delirium']))
print('Mean Squared Error:', metrics.mean_squared_error(test['delirium'], test['predicted delirium']))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(test['delirium'], test['predicted delirium'])))

R squared coefficient: 0.06514742160028231
Mean Absolute Error: 0.2514991281301739
Mean Squared Error: 0.1261192164980763
Root Mean Squared Error: 0.35513267450077907

In [47]:
##Sample Data

sample_train = pd.DataFrame(np.array([[1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 0, 1], [1, 1, 1, 0, 1, 1], [1, 1, 0, 1, 1, 1], [1, 0, 1, 1, 1, 1], [0, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 0], [1, 1, 1, 1, 1, 0]]), columns = ['benzodiazepine', 'opioid', 'anticholinergic', 'steroid', 'deep sedation', 'delirium'])

sample_test = pd.DataFrame(np.array([[1, 1, 1, 1, 1], [1, 0, 0, 0, 0], [1, 1, 1, 0, 1], [1, 1, 0, 0, 1], [1, 0, 0, 0, 1], [1, 0, 1, 0, 1]]), columns = ['benzodiazepine', 'opioid', 'anticholinergic', 'steroid', 'deep sedation'])

sample_variables = sample_train.drop(columns=['delirium'])
sample_output = sample_train['delirium']
sample_model = LinearRegression().fit(sample_variables, sample_output)

sample_predicted = sample_model.predict(sample_test)
sample_test['predicted delirium'] = sample_predicted
print(sample_train)
sample_test

   benzodiazepine  opioid  anticholinergic  steroid  deep sedation  delirium
0               1       1                1        1              1         1
1               1       1                1        1              0         1
2               1       1                1        0              1         1
3               1       1                0        1              1         1
4               1       0                1        1              1         1
5               0       1                1        1              1         1
6               1       1                1        1              1         0
7               1       1                1        1              1         0

,benzodiazepine,opioid,anticholinergic,steroid,deep sedation,predicted delirium
0,1,1,1,1,1,0.333333
1,1,0,0,0,0,3.000000
2,1,1,1,0,1,1.000000
3,1,1,0,0,1,1.666667
4,1,0,0,0,1,2.333333
5,1,0,1,0,1,1.666667